### ISSUE TITLE
Pre-Draft: Alternative Interfaces #1 Scholarships #2 Trust Funds

### ISSUE THREAD

**Issue by DunnCreativeSS** [Stakedllc/YIPs#24]
Part of the adoption problem for blockchain as a whole is in finding useful and productive uses for the protocols. 

Next is marketing.

When you have a working product that outperforms banks and keeps your $USD-backed money liquid (meaning you can withdraw it + interest at any time, or at different points in time) it opens the doors to all sorts of new SaaS, landing pages, marketing campaigns and a social legion of ambassadors ready to champion these new causes to their massive social following for some rewards.

1. If you slap a new face on 5-10% APR you can collect funds from people in a trustless manner and give out yearly payouts for a fixed amount of $ as scholarships, bursaries, etc. both anonymously and internationally - and even in a more democratic way, benefiting more than 1-2 students but maybe dozens of financially destitute ones - and at a fraction of the costs that the school's administrators would have you pay.

2. If you throw a bit of savings every week/year/bonus cheque into a multisig wallet whose equity grows with RAY, and lock the date by which that wallet can be accessed, you can now have a trust account for your little would-be millionaires who aren't quite age of majority yet. I know that if I were to pay my niece dividends from my legal corp she'd be taxed at 49%. I'm averse to banks and lawyers though - but still vested in her future. And I trust blockchain not to break and leave us all in the streets... so I set up a crypto educations fund.

These ideas are NOT custodial and we wouldn't need a license to run them. We'd simply set up a smart contract that says 1. enter funds here every so often 2. at pre-set dates the funds are send off to the 'award' addresses, who can do with them what they please. 

The smart contract would have functions to revoke future payments to an address, create a new address and allocate it a % of the regular or one-time payment, etc. (unless, as in the trust fund example, it'd make more sense to lock this behavior - but if it's multisig then if one party loses a signature we just create a new multisig).

The real trick isn't the tech that's there, it's figuring out a new & attractive design and then figuring a way to shift the paradigm in these two cases. As the generations move over there would be less and less speculation against doing things *traditionally.*

Whereas anyone studying here would hop at the chance: https://www.draperuniversity.com/

**Comment by dpurhar27** [comment]
This is a very cool idea and great use-case! This is a secondary layer product that could be built on-top RAY relatively easily. 

The main issue I'd see re: usage of this is that there is no insurance on funds deposited to RAY currently. This isn't an issue attached to RAY, but an issue attached to the general industry. I do believe such insurance will arise soon though. There is Nexus Mutual, but it has it's faults, mainly that it's a smart contract itself when the idea is to take out smart contract risk from the equation, and has not been tested before (paid out a claim). In other words, I think most target users would think it's too risky (at it's current stage). Of course, the risk is up to the user to decide to accept or not, and some may accept it.

Overall, cool use-case and I'd love to see something like this implemented eventually.

**Comment by DunnCreativeSS** [comment]
If only I had a % of a % of the people I refer to RAY I could use those funds to pay someone somewhere who's better with smart contracts to build it. Then pay more to market it!

Note that I'd already tried to find a business partner to build the scholarships portion of this suggestion:

![image](https://user-images.githubusercontent.com/22843601/74178391-e5b1a100-4c11-11ea-822b-bc3909332891.png)

I've become acquainted with the firm and Ether superstar that does Nexus. She had bid on the project I'm thinking about building that involves RAY. Her price is _too_ high for my budget, haha. As it should be!

**Comment by samatstaked** [comment]
Closing this issue because it is a product idea built on RAY, and want to focus on improving RAY's core functionality in this repo.
