### ISSUE TITLE
Pre-Draft: Curve Opportunity

### ISSUE THREAD

**Issue by samatstaked** [Stakedllc/YIPs#26]
Curve is a new automated market maker - similar to Uniswap - but Curve uses yield-generating stablecoins as it's liquidity source. Currently, Curve uses cUSDC/cDAI to market make between stablecoins. Liquidity providers are able to earn a higher return than just lending on Compound. 

This could be a very interesting opportunity for RAY. However, it is worth discussing what form an integration would take. So, I wanted to start a few items for discussion before a YIP was proposed.

**Primary item for discussion:** Do we want to integrate Curve as an opportunity, or potentially wait until RAY can be added as a liquidity source? i.e. rayTokens as a liquidity supply option versus cTokens? How would this look?

**Additional Items**: 1) Supplying cUSDC/cDAI to Curve is not risk-free, how do we hedge price risk?

**Additional Notes**: Curve has had high-returns as of late, (mid-teens), for liquidity suppliers. This is something we need to take into account. RAY's suppliers ultimately want the highest return possible.

**Comment by DunnCreativeSS** [comment]
Primary item for discussion: Couldn't it be both, or are they mutually exclusive? If we integrate with cTokens now it accelerates their liquidity and gives them more to play with and - in the future - support rayTokens. At that time, they could support both to help stave off counterparty risk - or remove the lesser-performing token?

1) is cDAI/cUSDC up and down in price primarily based on interest rate fluctuation? Or do they relate to underlying price of DAI / USDC?
2) Moon

**Comment by DunnCreativeSS** [comment]
Their UI could use a facelift.

**Comment by samatstaked** [comment]
Closing and Moving Discussions to Discord - https://discord.gg/am2W25V
