### ISSUE TITLE
Pre-Draft: Alternative Interfaces 2: Charities

### ISSUE THREAD

**Issue by DunnCreativeSS** [Stakedllc/YIPs#28]
With blockchain, we can create a factory contract that spits out children contracts.

In this proposition, we have a contract creator who's owner address can withdraw interest from the new contract - but only to a predefined 3rd party address.

In effect, this allows someone to start a multisig that then gains interest every year. Every year I deposit new amounts to the equity, instead of my regular contribution to whatever charity, and they earn the interest.

Now, my funds live on in perpetuity and will earn that charitable cause more funds than should they have been given the equity upfront.

They can optionally leave in a % of the accumulated interest, and that would achieve compounding growth.

**Comment by dpurhar27** [comment]
Cool, yes, I've been thinking about building something similar on my own time as a secondary layer product built on RAY 👍 

Note, this is a secondary-layer product, and not going to change the RAY's core.

**Comment by samatstaked** [comment]
Closing this issue because it is a product idea built on RAY, and want to focus on improving RAY's core functionality in this repo.
