### ISSUE TITLE
Pre-Draft: Alternative Interfaces 3: Teach Kids with Allowances

### ISSUE THREAD

**Issue by DunnCreativeSS** [Stakedllc/YIPs#29]
We can set up a contract where the withdrawal of capital is prohibited against until a certain date. Regular contributions will increase the interest yielded, which can be given (all or in part) to a young one as allowance - then their capital unlocks on some mandatory date (like turning 18) or by using keys for an event (like finishing school).

Even without much money as weekly allowance, the lesson of it growing over time as more is saved is a great lesson for children to experience as it applies to them. If a family isn't crypto-averse, an 18 year old could be getting $800 $1500 $2600 in interest alone - which would be financial freedom.

**Comment by dpurhar27** [comment]
Cool secondary-layer idea to be built on RAY! I certainly see all existing financial instruments like this (ie. college savings account) to be built on RAY one day. 

Current challenges around this are lack of insurance (think FDIC) on funds, and hard/expensive on/off-ramps.

**Comment by DunnCreativeSS** [comment]
I agree re: challenges, but as RAY continues to outperform traditional assets I think people will take notice :)

**Comment by samatstaked** [comment]
Closing this issue because it is a product idea built on RAY, and want to focus on improving RAY's core functionality in this repo.
