### ISSUE TITLE
YIP-2: Uniswap ETH/WETH Opportunity

### ISSUE THREAD

**Issue by dpurhar27** [Stakedllc/YIPs#5]
This is the discussion thread for [YIP-2](https://github.com/Stakedllc/YIPs/blob/master/YIPS/yip-2.md).

## Abstract
Add a new Opportunity for the ETH portfolios - the Uniswap ETH/WETH liquidity pool.

RAY strives to earn the best passive yield possible on assets supported. Adding this Opportunity will help do that for the ETH asset.

## Considerations
The current delay is a decision between waiting for Uniswap V2, or integrating with Uniswap V1 now.

**UPDATE:** We've decided to wait to integrate with Uniswap V2, which should be coming out mid-March. We don't need to wait as long to integrate with them because they're an exchange -> a less complex system, and don't have mechanisms such as liquidations, etc. that need to be tested through market volatility.

**Comment by samatstaked** [comment]
Updated YIP-2 to Uniswap V2 and moved discussion to Discord - https://discord.gg/qAsBaAM
